// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqhmmisiwytaztujdgli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxaG1taXNpd3l0YXp0dWpkZ2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzMyODYsImV4cCI6MjA3MzQ0OTI4Nn0.nx5_OAUZ_FAEiVL626ZYup6h1QLS9iEcxNGbW04dpXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});